servers:
  - url: http://127.0.0.1:5001
    name: worker-1
    weight: 1
  - url: http://127.0.0.1:5002
    name: worker-2
    weight: 1
  - url: http://127.0.0.1:5003
    name: worker-3
    weight: 1

health_check:
  interval_seconds: 5
  timeout_seconds: 2

load_balancer:
  port: 8000
  algorithm: least_connections
  log_level: INFO
